bcgov/parks-reso-api

lambda/readPass/index.js
BRS-144
https://bcmines.atlassian.net/browse/BRS-144
This ticket fixes a bug where the search filtering within facility passes would not return results if filtered by date. The issue was due to lambda function incorrectly parsing the date object. The JavaScript function `getMonth()` is zero-indexed and therefore the API was querying for dates 1 month prior to the one requested in the filtration widget.
=> BRS-144 fixing search by date on pass filters

lambda/deletePass/index.js
BRS-165
https://bcmines.atlassian.net/browse/BRS-165
I think I finally found the bug 😅 - hitting reload on the cancel page will lower the reservation count again.
Adds a check when cancelling a pass that it's not already in a cancelled state. This is needed to prevent multiple cancellations of the same pass from decrementing the reservation count multiple times.
=> BRS-165: only allow one pass cancellation

terraform/src/captcha.tf
Fix the wrong name used by the captcha private key secret.  New secret name has already been created in AWS
=> NOBUG: Fix captcha secret name

__tests__/checkActivation.test.js, __tests__/checkExpiry.test.js, lambda/checkActivation/index.js, lambda/checkExpiry/index.js, lambda/dynamoUtil.js, package.json, terraform/src/activationJob.tf, terraform/src/expiryJob.tf, yarn.lock
BRS-161
https://bcparksdigital.atlassian.net/browse/BRS-161
Run the cron hourly, and set passes to active depending on pass type and facility opening hour:
AM - activates at facility opening hour (default pulled from config)
PM - activates at 12pm
DAY - activates at facility opening hour (default pulled from config)
Expiry runs hourly but doesn't depend on the facility:
AM - 12pm
PM - 12am
DAY - 12am
Hourly is a bit more resource intensive but means that we don't have to update the schedule around DST changes (when the offset from PT to UTC will be different).
Status changes will only happen the same day (or day after for PM/DAY) expiry, so should be resistant to a few cron failures, but not a longer outage.
=> BRS-161: update pass activation logic

terraform/src/activationJob.tf, terraform/src/expiryJob.tf
These tasks run a lot of queries now, and have been timing out at 3 seconds.
=> NOBUG: set activation/expiry lambda timeouts to 5 min

lambda/writePass/index.js
Because ids are randomly generated and `putItem` will update if the key exists, if a collision does happen, the old pass with that duplicated id will be overwritten with data from the new pass.
Collisions are unlikely to happen (1/100 000 000 initially I think), but become more likely with each pass issued, so it's possible it will happen a few times during the season.
Note that if this does happen the user will get a generic "Operation Failed" error, but a retry will probably succeed.
=> NOBUG: don't update existing passes in case of id collision

lambda/writeFacility/index.js
Fixing issue with facility edit. Instead of using name as the SK, we don't allow SK to change. This is related to https://github.com/bcgov/parks-reso-api/commit/cd0d2ff68bd92dc0495a9ebf436da2f35fae5587.
=> NOBUG: Fixing facility edit duplication bug

lambda/readPass/index.js
BRS-218
https://bcparksdigital.atlassian.net/browse/BRS-218
This change adds API functionality to filter `readPass` results by `passStatus`.
To filter by one type of `passStatus`, 'active' for example:
* `GET .../api/pass?park=parkName&facilityName=facilityName&passStatus=active`
To filter by mutliple types of `passStatus`:
* `GET .../api/pass?park=parkName&facilityName=facilityName&passStatus=expired,cancelled,reserved`
=> BRS-218: multiselect passStatus - API

__tests__/writePass.test.js, lambda/writePass/index.js
BRS-294
https://bcparksdigital.atlassian.net/browse/BRS-294
This change sets `passStatus` to `active` when creating/booking a pass during active hours. 
Currently the default action is to set `passStatus` to `reserved` regardless of when the pass is created/booked. This is causing active passes incorrectly marked as `reserved` to be overlooked by the crons, therefore never getting set to `active` or `expired`. This causes passes that should be expired to appear as reserved.
Additionally, the API still allows passes to be booked for days that have already passed, or for AM passes to be booked after the PM timeslot begins. This change adds API functionality to check and reject booking requests for times that fall outside of reservable/active hours.
The test suite has been updated to capture …
=> BRS-294: passStatus set to active if booking during active hours

lambda/readPass/index.js, lambda/writePass/index.js, migrations/caseInsensitiveNames.js
BRS-196
https://bcparksdigital.atlassian.net/browse/BRS-196
This change allows for case-insensitive searching for first and last names on passes. DynamoDB is not able to do this internally, so best practice is to create a secondary searching field when creating passes that is the field you want to search on, cast to lowercase. When searching, the API searches on the lowercase field. This change adds the fields `searchFirstName` and `searchLastName` to passes when creating, and searches on these fields when the API queries for `firstName` and `lastName`.
There is a migration to update all historical passes with the new search fields.
To run locally, ensure `dynamodb-local` db is running in a docker instance or similar, navigate to `/migrations` and run
```
export IS_OFFLINE=1
node …
```
=> BRS-196 - case insensitive search on first and last names

serverless.yml
BRS-468
https://bcparksdigital.atlassian.net/browse/BRS-468
Site metrics on DUP showing error message and not loading.  This bumps the memory up so we get more vCPUin our lambda.  New execution time is < 6000ms
=> BRS-468: Bump memory limit for more vCPU

lambda/cloudwatchAlarm/index.js, serverless.yml, terraform/src/cloudwatchAlarms.tf, terraform/src/params.tf
BRS-275
https://bcparksdigital.atlassian.net/browse/BRS-275
This creates a number of new infrastructure items:
- Cloudwatch: Alarm for Lambda Error Invocations
- SNS: Topic for Cloudwatch to send SNS notifications so they can be picked up by a SQS
- SQS: Handling SNS -> SQS messages, so that we can call a lambda to respond
- Lambda: SQS processing function, which sends events to RocketChat so that we can get notified about invocation errors
- Variables `aws_account_list`, `rocketchat_url`, `rocketchat_bearer_token`: For handling the webhook details.  These are already pre-seeded in each of our environments `sandbox`, `dev`, `test`, `prod`.
When lambdas error out unexpectedly, cloudwatch will sense that and send an SNS message, which the SQS queue picks up, and delivers to our lambda …
=> BRS-275: Invocation error trigger for Lambda

lambda/readPass/index.js, lambda/writePass/index.js
BRS-296
https://bcparksdigital.atlassian.net/browse/BRS-296
Some screens were missed in the original change. API now passes `date` and `type` to the intermediate cancellation screen via the URL. It also passes `parkName`, `facilityName` and `date` to the GCN API when triggering cancellation emails.
##IMPORTANT: GCN PROD cancellation email templates need updating upon this change hitting the PROD env.
Note: this PR should be passed before https://github.com/bcgov/parks-reso-public/pull/129
=> BRS-296-2: showing date in more places

__tests__/writePass.test.js, lambda/writePass/index.js
BRS-658 
This change is part 1 of several that involve fortifying the back end against time zone spoofing. 
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our `writePass` lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`. 
Additionally, the portion of `writePass` that checks for existing passes was fortified to check only the date portion of the ISO date object so that each email address may have a maximum of 1 pass per given day (before, passes booking for `2022-06-09T19:00:00.000Z` and `2022-06-09T19:00:01.000Z` would fail the 'same-day' check).
=> BRS-658 fixing time zone issues for writePass.js

lambda/readPass/index.js
BRS-658
This change is part 2 of several that involve fortifying the back end against time zone spoofing.
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our `readPass` lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`.
=> BRS-658: fixing time zone issues in readPass.js

__tests__/checkExpiry.test.js, lambda/checkExpiry/index.js
BRS-658
This change is part 3 of several that involve fortifying the back end against time zone spoofing.
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our checkExpiry lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`.
This change addresses a bug where tests would fail if they were run late in the day PST time (next day UTC dates were causing issues). 
The `mockdate` package was investigated and found to be NOT succeptable to the same `date-fns`/`date-fns-tz` issues related to BRS-658.
=> BRS-658 fixing time zone issues in checkExpiry.js

__tests__/checkActivation.test.js, lambda/checkActivation/index.js
BRS-658
This change is part 4 of several that involve fortifying the back end against time zone spoofing.
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our `checkActivation` lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`.
=> BRS-658 fixing timezone issues in checkActivation.js

lambda/exportPass/index.js
BRS-658
This change is the 7th and final change that involves fortifying the back end against time zone spoofing.
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our `exportPass`  lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`.
=> BRS-658 fixing timezone issues in exportPass.js

lambda/dynamoUtil.js
BRS-658
`timeZone` and `TIMEZONE` both equal the same thing.
=> BRS-658 removing duplicate timezone declarations in dynamoUtil

terraform/src/cloudwatchAlarms.tf
This enables more verbose logs in the cloudwatch alarm lambda.
=> NOBUG: Enable debug logs for cloudwatch alarms

lambda/dynamoUtil.js
NOBUG
Updated `getPark` and `getFacility` functions were interpreting an unmarshalled `visible` field. 
`Boolean(visible)` where `visible: {BOOL: false}` was equating to true. This has now been fixed to equate to false.
=> NOBUG - fixing unmarshalled visibility check in dynamoUtils

__tests__/writePass.test.js, lambda/writePass/index.js
BRS-595
https://bcparksdigital.atlassian.net/browse/BRS-595
This change alters the `writePass` endpoint to give sysadmins special privileges when creating passes. An authorized sysadmin can now book up to the available facility capacity, and can bypass certain checks.
Sysadmins do not need to provide a valid captcha JWT.
Sysadmins can book above the maximum number of guests allowed on a single public pass.
Sysadmins can book any date in the future.
Sysadmins cannot book a date in the past.
Sysadmins cannot overbook a facility.
Below is an example of the simplified payload a sysadmin can send to the `writePass` endpoint.
```
POST .../api/pass
{
"numberOfGuests": 8,
"lastName": "Bulk",
"facilityName": "Cheakamus",
"email": "bulkbooking@recipient.com",
"firstName": "Booking",
"date": …
```
=> BRS-595 allowing sysadmins to bulk book passes

lambda/readPass/index.js
BRS-729
https://bcparksdigital.atlassian.net/browse/BRS-729
Based on my testing, searching by reservation number never worked (it didn’t work sometimes as stated in the ticket title)  
The actual error was **“Conditions can be of length 1 or 2 only”**
This query was causing the error:
```
{
"TableName":"parksreso",
"ExpressionAttributeValues":{
":shortPassDate":{
"S":"2022-07-21"
},
":facilityName":{
"S":"Test"
},
":passType":{
"S":"DAY"
},
":sk":{
"S":"055291844"
}
},
"IndexName":"shortPassDate-index",
"KeyConditionExpression":"shortPassDate =:shortPassDate AND facilityName =:facilityName AND sk =:sk",
"FilterExpression":"#theType =:passType",
"ExpressionAttributeNames":{
"#theType":"type"
}
}
```
I moved the ` AND sk =:sk` check from `KeyConditionExpression` to `FilterExpression` to and …
=> BRS-729: Error searching by reservation number

lambda/readReservation/index.js
BRS-761
https://bcparksdigital.atlassian.net/browse/BRS-761
This change allows `readReservation` to create a booking time object if it doesn't previously exist.
=> BRS-761-2 allow readReservation to create time slot if it doesnt exist

lambda/writePass/index.js
BRS-776
https://bcparksdigital.atlassian.net/browse/BRS-776
During pass creation, we run a query to see if the user has already booked under that email/bookingTime/facility combination, and refuse pass creation if they've already booked. 
In PROD, there are so many passes per facility now, that the query is timing out before completing. When it fails, the existing pass check is bypassed (because no matches were found), allowing prod users to book multiple passes under the same parameters.
This change improves the query efficiency by using the `shortPassDate-index` to drastically minimize the pool of passes to search for duplicates on.
=> BRS-776: improving existing pass query efficiency

lambda/reservationObjUtils.js
NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-123
Sending passes to the overbooked state was resulting in sending all passes to overbooked due to a missing `break` clause.
=> NOBUG - editing mods doesn't overbook entire passlist

__tests__/writePass.test.js, lambda/readReservation/index.js, lambda/reservationObjUtils.js, lambda/writeFacility/index.js, lambda/writeModifier/index.js, lambda/writePass/index.js, lambda/writeReservation/index.js
BRS-774
https://bcparksdigital.atlassian.net/browse/BRS-774
For accuracy of historical data, we need to ensure a new resObj is created if one doesn't exist every time the following fields of a facility are updated:
- capacity change
- modifier change
- timeslot is opened/closed
- facility is opened/closed
This change also introduces the facility open/closed status on reservation objects. If a facility opens/closes, all present & future resObjs will be updated with the new open/closed status. 
Some minor code refactoring was also done for ease of adding new fields to the resObj in the future.
=> BRS-774: always create resObj when editing facility

tools/dynamoPurge.js
NOBUG
Our dbs in dev/test/prod are getting quite large and can be very time consuming to drop/reseed owing to the large number of passes. Adding a `dynamoPurge.js` script to wipe all passes & reservation objects from your local database, so you can create far smaller data dumps when needed.
To use: navigate to `/tools` and run `node dynamoPurge.js`. All passes & resobjs at localhost:8000 will be deleted.
=> NOBUG - adding dynamodb purge tooling

.github/workflows/PR-Tests.yaml
NOBUG
Upgrading GH actions to run Node16.
https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/
=> GH Actions upgrade to Node16

lambda/dynamoUtil.js, lambda/gcNotifyUtils.js, lambda/rocketChatUtils.js, lambda/sendReminder/index.js, package.json, serverless.yml, terraform/src/params.tf, terraform/src/reminderJob.tf, tools/rocketchat-script-example.js, yarn.lock
BRS-566
https://bcparksdigital.atlassian.net/browse/BRS-566
This change introduces a cronjob that fires every day at 00:00 UTC (16:00 or 17:00 PT). When fired, it collects every `reserved` pass for every park 1 day in advance, then sends a reminder email to those passes using GCN. 
The service can be turned off by changing the `aws_ssm_parameter = gc-notify-is-sending-reminders` to anything but `'true'` in all environments. 
Also added in this PR: Utils for GCN and RocketChat.
GCN Utils: Added a util that leverages `axios` to perform an http POST to GCN. You must provide the GCN template url, API key, and request body. Refer to GCN's API documentation to learn the structure of the request body. The util `gcnSend` can be used for both single and bulk email calls, though the request body …
=> BRS-566 Adding booking reminder email service

lambda/dynamoUtil.js, lambda/sendReminder/index.js, terraform/src/db.tf, terraform/src/params.tf, terraform/src/reminderJob.tf, terraform/src/roles.tf
BRS-566
https://bcparksdigital.atlassian.net/browse/BRS-566
This change introduces a new `dynamodb` table `parksreso-meta` for containing system metadata like `sendReminderSummary` job objects.
Developers: for your `.bashrc` convenience:
```
aws dynamodb create-table \
--table-name parksreso-meta \
--attribute-definitions \
AttributeName=pk,AttributeType=S \
AttributeName=sk,AttributeType=S \
--key-schema \
AttributeName=pk,KeyType=HASH \
AttributeName=sk,KeyType=RANGE \
--billing-mode PAY_PER_REQUEST \
--provisioned-throughput \
ReadCapacityUnits=1,WriteCapacityUnits=1 \
--region local-env --endpoint-url=http://localhost:8000/
```
=> BRS-566: giving reminderJob write perms

tools/capacityReport.js
BRS-901
https://bcparksdigital.atlassian.net/browse/BRS-901
This change includes a developer script in the `/tools` directory that generates a 'capacity report' - it surfaces reservation data when given park, facility, startDate, and endDate. The script can export to JSON or csv.
To run: `node capacityReport.js <export filetype> <park> <facility> <startDate> <endDate>`
the `endDate` argument is optional. If no endDate is provided, the script will return data for only the `startDate` day.
The script will only return data for dates which have a `reservation` object in the database. If no reservation object exists, it means that no data changes occurred for that facility on that day. It can be assumed that values like `baseCapacity` are the same as they were on the closest previous existing …
=> BRS-901: developer script to collect reservation information

lambda/exportPass/index.js
BRS-916
https://bcparksdigital.atlassian.net/browse/BRS-916
Note that this change, in accordance with ticket BRS-916, only removes the audit trail from the exporter on the facility's pass list page. The metrics page exporter still exports audit trail information.
=> BRS-916: removing audit trail from pass export

tools/pksk-migration/parks/common.js, tools/pksk-migration/parks/create.js, tools/pksk-migration/parks/delete.js
BRS-794
https://bcparksdigital.atlassian.net/browse/BRS-794
This change adds in the migration scripts that will update the primary keys of all items in the db to reflect the new proposed updates to park sk changes only. The scripts are being added now to break up the amount of review required, but the scripts will not be run until the API/FE changes are complete and ready to merge.
Since you cannot update the pk/sk of an item in dynamodb, we will have to create brand new items. This means we will have to create a new item with the correct pk/sk for nearly every item in the database, and then delete the old ones.
=> BRS-794 Part 1: idempotent migration scripts

lambda/sendSurvey/index.js, serverless.yml, terraform/src/db.tf, terraform/src/params.tf, terraform/src/surveyJob.tf
BRS-934
https://bcparksdigital.atlassian.net/browse/BRS-934
This change adds the survey email feature to DUP. The service is toggled by AWS Parameter `GC_NOTIFY_IS_SENDING_SURVEYS='true'`.
Other AWS Parameters to include:
```
GC_NOTIFY_SURVEY_TEMPLATE_ID
FEEDBACK_SURVEY_URL
```
This change reuses a considerable amount of code from the `sendReminder` email service. It runs on a cronjob that fires at 1200 PST (1300 PDT), collects all expired passes from the previous day (currently hardcoded to do this only for Mt. Seymour), and leverages GCN's Bulk Email API to deliver the surveys.
=> BRS-934: park visitor survey email

terraform/src/reminderJob.tf
BRS-1015/BRS-1068
https://bcparksdigital.atlassian.net/browse/BRS-1015
BRS-1068 was created to handle this but it is technically part of BRS-1015. Now that reminder email templates differ whether the facility supports QR codes or not, Terraform needs to pull in the `QR_CODE_ENABLED` env var, which was missed on the first pass through.
=> BRS-1015-2: adding QR code enabled var to reminder email tf

terraform/src/main.tf
This adds the permission needed to have the sendReminder function to write to cloudwatch
=> NOBUG: Adds logging to send reminder lambda.

__tests__/global/settings.js, __tests__/metrics.test.js, lambda/dynamoUtil.js, lambda/metricsUtils.js, lambda/readMetrics/index.js, lambda/writeMetrics/index.js, serverless.yml, terraform/src/db.tf, terraform/src/main.tf, terraform/src/metric.tf, terraform/src/metrics.tf, terraform/src/metricsJob.tf, terraform/src/params.tf, terraform/src/roles.tf, tools/backfillMetrics.js
BRS-1020
https://bcparksdigital.atlassian.net/browse/BRS-1020
This change is the API portion of BRS-1020. The accompanying admin side changes will follow.
This change adds 3 major areas of functionality to the API:
1. A new lambda `writeMetrics` that runs on a 5 minute cronjob. When `writeMetrics` is run, all parks and facilities are checked for changes on the current day, plus any days into the future where there exists a reservation object for that facility. The data from passes and reservations objects for all the facilities are collated and stored in a daily metrics item in a new `parksreso-metrics` table with the following primary key:
```
pk: metrics::<parkORCS>::<Facility Name>
sk: shortDate
```
Because this lambda is run every 5 minutes, existing metrics objects will be …
=> BRS-1020 - new metrics API

terraform/src/warmUp.tf
This just drops the concurrency on the warm up functions.
=> NOBUG: Reducing warmup function concurrency.

package.json, serverless.yml, yarn.lock
BRS-1139
This removes `date-fns-tz` as it was no longer a dependency and updates another package from a potentially breaking change.
=> BRS-1139: Updating package versions.

lambda/writePark/index.js
BRS-267 - Add safety video to Park Information
Links to DUP-PUBLIC PR: https://github.com/bcgov/parks-reso-public/pull/269
Links to DUP-ADMIN PR: https://github.com/bcgov/parks-reso-admin/pull/304
https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=39881272
Added logic to handle video links being added to parks during PUT request. Can only be done through DUP-ADMIN when editing an existing park.
=> BRS: 267 - Add Safety Video To Park DUP

lambda/dataRegisterUtils.js
PDR-288
Relates to https://github.com/bcgov/parks-reso-api/issues/288
Partially fixes the issue where the nightly fetch script would not collect updated name data from the data registry. The original PR was submitted before the Authorizer code landed, which changed how the data register provides name data slightly. The data register now requires an `Authorization` header, even if no auth token is provided. This has been added in in this change.
The nightly update will still not work due to https://github.com/bcgov/parks-data-register/issues/167. The data register will allow the first park to be updated but will deny all future calls as the endpoints are different between parks.
=> PDR-288-1 adding Authorization to Axios headers for updateParkName

lambda/writePark/index.js
BRS-311
Links to [DUP - Admin - 313](https://github.com/bcgov/parks-reso-admin/pull/313)
[DUP Admin -> The "Park name" should be read only in edit mode.#311](https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=42084240)
Removed updating park name through api writePark function
=> BRS-311: Disable edit park name through DUP Admin

README.md, lambda/dataRegisterUtils.js, terraform/src/updateParkName.tf, terraform/src/variables.tf
This adds the header to the data register integration request. Parameter store contains the value and is injected into the environment vars for the name update cronjob.
=> 122: Adding x-api-key for data register integration.

lambda/passUtils.js
[BRS-280](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42572823)
Links to: [Public PR](https://github.com/bcgov/parks-reso-public/pull/269)
[https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42572823](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42572823)
Changed the PM start time to noon which will make AM passes expired at the time.
=> BRS-280: Adjust AM pass expiry

lambda/metricsUtils.js, lambda/reservationObjUtils.js
Completes #309.
When reservation objects are updated, they now capture additional metrics: 
- status: the state of the facility (open || closed)
- passesRequired: whether or not passes are required on the date, based on `bookingDays` and `bookableHolidays` attributes of the facility.
Note that a status of `closed` does not mean passes are not required. They are two mutually exclusive properties.
With this new addition, metrics objects now also capture `status` and `passesRequired` values. These are now included in the metrics csv that can be downloaded from the metrics route in DUP admin (captured in a different PR).
=> PDR-309 adding status and passesRequired to metrics csv

__tests__/checkExpiry.test.js, lambda/checkExpiry/index.js
Fixes PDR-346 https://github.com/bcgov/parks-reso-api/issues/346
`checkExpiry` cronjob runs every hour. When it runs after 18:00, all active passes in the system are set to `expired` instead of waiting until midnight to do this.
=> PDR-346 expire DUP passes at 6pm same day

samNode/handlers/writePass/__tests__/writePass.test.js, samNode/layers/metricsLayer/metricsLayer.js, samNode/layers/reservationLayer/reservationLayer.js, tools/dynamoRestore.js
BRS-312
[#312](https://github.com/bcgov/parks-reso-admin/issues/312)
- Ensures that if a park is closed, passes are not required.
- Adjusts capacity calculations to set capacity and available passes to zero if passes are not required.
- Fixes potential issues in the `checkPassesRequired` function by ensuring `bookableHolidays` is treated as an array and optimizing the logic for determining pass requirements.
- Updates reservation object creation to correctly apply the passes-required logic.
- Changes the default table name from `parksreso` to `ParksDUP`.
- Ensure the final batch is processed
=> BRS-312: Fix Site Metrics Results when Facilities were Noted as "Pass Not Required"

samNode/template.yaml
Ticket: [504](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=104931620&issue=bcgov%7Cparks-reso-public%7C504)
Notes: This is just an adjustment for the cron schedule. There will need to be an update to the expiry times (FE + BE) before DUP is active again in may.
=> BRS-504: Daylight savings 2025

samNode/template.yaml
BRS-438
#438 
- Fix time for cron, can't go to `24` in a cron
=> BRS-438-2: Make Metrics Cronjob Permanent

samNode/layers/__tests__/reservationLayer.test.js, samNode/layers/reservationLayer/reservationLayer.js
BRS-312
[#312](https://github.com/bcgov/parks-reso-admin/issues/312)
- Fix so the facility's status affects passes required when facility is 'open' or 'closed'
- Add missing test
=> DUP-312-Sendback-1: Fix to Facility Status

samNode/layers/__tests__/reservationLayer.test.js, samNode/layers/reservationLayer/reservationLayer.js
BRS-312
[#312](https://github.com/bcgov/parks-reso-admin/issues/312)
- Rewrite tests to follow testing pattern, as outlined [here](https://github.com/bcgov/parks-reso-admin/issues/312#issuecomment-2847766401).
- Fix an issue with checking the park status, now correctly finds the park's status in the `park` object
=> DUP-312-Sendback-2: Properly Checks Park Status

samNode/handlers/sqsProcessor/__tests__/sqsProcessor.test.js, samNode/handlers/sqsProcessor/index.js
Ticket : [469](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=122041932&issue=bcgov%7Cparks-reso-api%7C469)
Notes: Updated the handler which sends the emails to retry once if a 503 is returned. This is the error GCN is returning in the middle of our batch sends. 
Added a bunch more tests to encapsulate this functionality.
=> BRS-469: Retry 503 once
