.gitignore, tf-lambda/pass.tf, tf-lambda/variables.tf, tools/.gitignore, tools/dynamoMigrator.py, writePass/index.js
https://bcmines.atlassian.net/browse/FLCN-128
=> FLCN-128: added email receipt to write pass

readPass/index.js, readPass/package-lock.json, tf-lambda/pass.tf, tf-lambda/variables.tf, tools/README.md, tools/dynamoMigrator.py, writePass/index.js, writePass/package-lock.json
https://bcmines.atlassian.net/browse/FLCN-156
to test use the blow postman collection. write pass will create a pass in the sandbox env and  send you an email receipt. then call the read pass which is called when you load the pass-lookup page. this will send you the cancelation email with the JWT link
```
{
"info": {
"_postman_id": "e77a1a74-15a2-4e80-a964-aafa217cd696",
"name": "Test Email in Sandbox env",
"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
},
"item": [
{
"name": "Create Pass Sandbox",
"request": {
"method": "POST",
"header": [],
"body": {
"mode": "raw",
"raw": "{\r\n    \"numberOfGuests\": 2,\r\n    \"lastName\": \"someLastname\",\r\n    \"facilityName\": \"Diamondhead\",\r\n    \"email\": \"max.wardle@gov.bc.ca\",\r\n    \"firstName\": …
```
=> FLCN-156: added cancellation email with JWT link

.github/workflows/deploy-dev.yaml
Reverts bcgov/parks-reso-api#15
=> Revert "Removing working directory for terragrunt"

.github/pull_request_template.md, lambda/writePass/index.js
BRS-168
https://bcparksdigital.atlassian.net/browse/BRS-168
This PR enforces unique pass bookings by email, facility, type and date.
=> BRS-168 Prevent duplicate pass booking

lambda/writePass/index.js
BRS-140
https://bcparksdigital.atlassian.net/browse/BRS-140
Formatting the date sent to confirmation emails.
=> BRS-140 formatting date string for emails

lambda/writeFacility/index.js
BRS-148
https://bcparksdigital.atlassian.net/browse/BRS-148
Adds `bookingOpeningHour` and `bookingDaysAhead` to the facility object on write. This data will allow setting of a per facility booking window in the admin, and checking it in public.
=> BRS-148: add facility booking window fields

lambda/deletePass/index.js
BRS-165
https://bcparksdigital.atlassian.net/browse/BRS-165
Also wrap pass and facility updates in a transaction so they don't get out of sync.
=> BRS-165: fix counters when cancelling via admin

__tests__/writePark.test.js, lambda/writePark/index.js, package.json, serverless.yml, terraform/src/main.tf, yarn.lock
BRS-211
https://bcparksdigital.atlassian.net/browse/BRS-211
This adds a `PUT` resource into the writePark api.  There is another PR in the admin repo that needs to combine with this PR (it is also tagged with BRS-211).  No longer can the front-end admin call POST to `edit` park details.
This also adds JEST to as unit tests.  Run the first batch by `yarn run jest --coverage`
=> BRS-211: Duplicated Park in DUP was created when editing park details.

lambda/writeFacility/index.js
BRS-148
https://bcparksdigital.atlassian.net/browse/BRS-148
Allow allow same (0) day booking window in the API.
=> BRS-148: allow same (0) day booking window

.gitignore, README.md, __tests__/captchaHandler.test.js, __tests__/writePark.test.js, lambda/captcha/handler.js, lambda/captchaUtil.js, lambda/writePass/index.js, package.json, serverless.yml, terraform/src/activationJob.tf, terraform/src/captcha.tf, terraform/src/expiryJob.tf, terraform/src/facility.tf, terraform/src/main.tf, terraform/src/modules/cors-enabled-api-resource/main.tf, terraform/src/modules/cors-enabled-api-resource/outputs.tf, terraform/src/modules/cors-enabled-api-resource/variables.tf, terraform/src/pass.tf, terraform/src/roles.tf, terraform/src/settings.tf, terraform/src/variables.tf, tools/README.md, tools/dynamoRestore.js, tools/generateCaptchPrivateKey.js, yarn.lock
BRS-199 
https://bcparksdigital.atlassian.net/browse/BRS-199 
- Add captcha endpoints.  The audio endpoint requires valid AWS credentials in env when testing locally
- Fixed Terraform config for Park PUT endpoint
- Updated Nodejs runtime to v14
=> BRS-199 Add captcha

__tests__/writeFacility.test.js, lambda/writeFacility/index.js, serverless.yml, terraform/src/facility.tf, terraform/src/main.tf
The admin API call was switched over to PUT from POST in https://github.com/bcgov/parks-reso-admin/pull/70, but it's not yet supported for the facility endpoint, so facility edits are getting a 403 from API Gateway. Fix that by using PUT to update, as with the park endpoint.
=> NOBUG: support facility PUT calls

terraform/src/facility.tf
Fix config issues with previous change.
=> NOBUG: fix terragrunt

lambda/writePark/index.js
BRS-248
https://bcparksdigital.atlassian.net/browse/BRS-248
Add `mapLink` param to park API endpoint.
=> BRS-248: add mapLink to park API endpoint

lambda/writePark/index.js
These attributes are nested inside the `park` object in the payload.
=> NOBUG: fix update park status, capacity, link

.gitignore, __tests__/writePass.test.js, lambda/writePass/index.js, yarn.lock
BRS-248
https://bcparksdigital.atlassian.net/browse/BRS-248
Adds more UT's, `mapLink` and `parkName` to the template variables sending off to GCN.
=> BRS-248: Add map url to park in DUP.

package.json
Serverless doesn't package devDependencies.
=> NOBUG: date-fns is a runtime dependency

terraform/src/db.tf
BRS-249
https://bcparksdigital.atlassian.net/browse/BRS-249
This enables data backups for dynamo and a simple retention policy.
=> BRS-249: Data Backups.

terraform/src/db.tf
BRS-249
https://bcparksdigital.atlassian.net/browse/BRS-249
Update tf field.
=> BRS-249: Fix field.

lambda/checkActivation/index.js, lambda/checkExpiry/index.js
BRS-161
https://bcparksdigital.atlassian.net/browse/BRS-161
Park name and sk don't always match (e.g. "Seymour Provincial Park" vs "Mount Seymour Provincial Park")
=> BRS-161: use sk, not name for lookup

terraform/src/pass.tf
BRS-292
https://bcparksdigital.atlassian.net/browse/BRS-292
CORs error reoccuring on email cancellation process
=> BRS-292: CORs error reoccuring on email cancellation process

lambda/writePass/index.js
BRS-267
https://bcparksdigital.atlassian.net/browse/BRS-267
Setting error language for when pass is unavailable.
=> BRS-267: Setting error language for when pass is unavailable.

lambda/readPass/index.js
Enable search by email on passes.
=> NOBUG: enable search by email on passes

tools/ssmExtractor.js, tools/ssmInjector.js
NOBUG
This helps in secrets and parameterStore tooling (extract/inject)
=> NOBUG: Adding param/secret extraction and injection tools.

lambda/writePass/index.js
BRS-356
https://bcparksdigital.atlassian.net/browse/BRS-356
Adding shortPassDate to passes. This will be used for indexing.
=> BRS-356: Adding shortPassDate to passes

.gitignore, lambda/deletePass/index.js, lambda/exportPass/index.js, lambda/permissionUtil.js, lambda/readPass/index.js, lambda/writeConfig/index.js, lambda/writeFacility/index.js, lambda/writePark/index.js, package.json, serverless.yml, terraform/common.auto.tfvars, terraform/sandbox/terragrunt.hcl, terraform/src/db.tf, terraform/src/export.tf, terraform/src/main.tf, terraform/src/params.tf, terraform/src/roles.tf, terraform/src/variables.tf, yarn.lock
BRS-311
https://bcparksdigital.atlassian.net/browse/BRS-311
This adds server side CSV generation to our back end, delivers to S3, and returns a signed URL to the user to fetch the payload directly.  Front end PR will follow.
=> BRS-311: Server side CSV generation /w S3 link.

lambda/dynamoUtil.js, lambda/metric/index.js, serverless.yml, terraform/src/metric.tf, terraform/src/roles.tf
NOBUG
This supports the metrics front-end graph for admin.  PR for admin side here: https://github.com/bcgov/parks-reso-admin/pull/88
=> NOBUG: Adding metrics endpoint.

lambda/deletePass/index.js, lambda/dynamoUtil.js, lambda/readPass/index.js, lambda/writePass/index.js, migrations/20220119155039-shortPassDate.js, serverless.yml, terraform/src/db.tf
BRS-356
https://bcparksdigital.atlassian.net/browse/BRS-356
Adding GSI for shortPassDate.
=> BRS-356: Adding GSI for shortPassDate

terraform/src/db.tf, terraform/src/params.tf
=> NOBUG: Fixing Terraform

terraform/src/db.tf
=> NOBUG: Defining attributes

terraform/src/roles.tf
Fixing read perms for indexes.
=> NOBUG: Fixing read perms for indexes

lambda/readFacility/index.js, lambda/readPark/index.js
This fixes the lookups on the token object coming back from the utility class.
=> NOBUG: Fixing permission lookups.

__tests__/checkExpiry.test.js, __tests__/global/setup.js, lambda/checkExpiry/index.js, package.json, serverless.yml, terraform/src/db.tf, yarn.lock
BRS-425
https://bcparksdigital.atlassian.net/browse/BRS-425
This updates the logic for pass expiry checks, including fixing unit tests to be more precise.
=> BRS-425: Update logic for pass expiry checks.

terraform/src/pass.tf
NOBUG
Tweak timeouts for writePass.
=> NOBUG: Fix timeouts for writepass

serverless.yml
NOBUG
Tweaking memory settings.
=> NOBUG: Update mem settings.

lambda/captcha/handler.js, lambda/readConfig/index.js, lambda/readFacility/index.js, lambda/readPark/index.js, lambda/responseUtil.js, lambda/writePass/index.js
BRS-123
https://bcparksdigital.atlassian.net/browse/BRS-449
Adding lambda warmup responses to public functions.
=> BRS-449: adding lambda warmup responses to public functions

lambda/responseUtil.js, lambda/warmUp/index.js, lambda/warmUp/readme.md, lambda/warmUp/worker.js, serverless.yml, terraform/src/captcha.tf, terraform/src/export.tf, terraform/src/facility.tf, terraform/src/main.tf, terraform/src/metric.tf, terraform/src/pass.tf, terraform/src/roles.tf, terraform/src/settings.tf, terraform/src/warmUp.tf
BRS-449
https://bcparksdigital.atlassian.net/browse/BRS-449
* Creating warmup functionality for Lambda.
* Fixing issues where memory size was not being set
* Setting timeouts for some functions.
* Adding provisioned concurrency on public functions
* Adding timeouts to fix race condition in terraform for provisioned concurrency
=> BRS-449: creating warmup functionality for Lambda

lambda/warmUp/readme.md, package.json, yarn.lock
BRS-449
https://bcparksdigital.atlassian.net/browse/BRS-449
Adding missing dependency.
=> BRS-449: Adding missing dependency

terraform/src/export.tf, terraform/src/facility.tf, terraform/src/main.tf, terraform/src/metric.tf, terraform/src/params.tf, terraform/src/pass.tf, terraform/src/settings.tf
NOBUG
Adding var for sso_issuer and sso_jwksuri.
=> NOBUG: Adding var for sso_issuer and sso_jwksuri

lambda/deletePass/index.js
BRS-296
https://bcparksdigital.atlassian.net/browse/BRS-296
This change attaches the pass object to the API response when cancelling a pass.
This change is required for https://github.com/bcgov/parks-reso-public/pull/126.
=> BRS-296 sending pass information with successful pass cancellation

lambda/permissionUtil.js
BRS-597
https://bcparksdigital.atlassian.net/browse/BRS-597
This changes the back-end to look at the parks-pass client based roles.  All environments have oidc changes ready.
=> BRS-597: client based role approach

package.json, yarn.lock
=> NOBUG: Package updates.

lambda/writePass/index.js
BRS-624
https://bcparksdigital.atlassian.net/browse/BRS-624
Minor changes to the API to reflect desired changes in the GCN template:
`date` is now separated into `date` ('May 24, 2022') and `type` ('AM/PM/DAY')
`parksLink` is now provided, including a link to the relevant bcparks page (managed from the admin portal)
=> BRS-624 update DUP email with summer text

lambda/readPass/index.js, lambda/writePass/index.js
BRS-624
https://bcparksdigital.atlassian.net/browse/BRS-624
Changing the `personalization` object passed to the GCN api to contain the wording 'ALL DAY' in the case of DAY passes. 
Also fixed a regression error where some URL params were not being attached to the cancellation link.
=> BRS-624 change email wording DAY to ALL DAY

lambda/deletePass/index.js, lambda/dynamoUtil.js, lambda/exportPass/index.js, lambda/logger.js, lambda/metric/index.js, lambda/permissionUtil.js, lambda/readFacility/index.js, lambda/readPark/index.js, lambda/readPass/index.js, lambda/writeConfig/index.js, lambda/writeFacility/index.js, lambda/writePark/index.js, package.json, yarn.lock
BRS-299
https://bcparksdigital.atlassian.net/browse/BRS-299
Switches to use client-based roles instead of realm based roles.  There are no park operator specific changes, just sysadmin.
=> BRS-299: Roles use client-based roles, instead of realm based roles.

package.json
BRS-658
Adding `luxon` to `package.json`
=> BRS-658 adding luxon package

lambda/deletePass/index.js
BRS-658
This change is part 6 of several that involve fortifying the back end against time zone spoofing.
This change addresses the 4 time zone issue outlined in https://bcparksdigital.atlassian.net/browse/BRS-651 for our `deletePass` lambda only. The packages `date-fns` and `date-fns-tz` are removed and replaced with `luxon`.
=> BRS-658 fixing timezone issues in deletePass.js

lambda/captchaUtil.js, lambda/checkActivation/index.js, lambda/checkExpiry/index.js, lambda/cloudwatchAlarm/index.js, lambda/deletePass/index.js, lambda/dynamoUtil.js, lambda/exportPass/index.js, lambda/logger.js, lambda/metric/index.js, lambda/permissionUtil.js, lambda/readConfig/index.js, lambda/readFacility/index.js, lambda/readPass/index.js, lambda/writeConfig/index.js, lambda/writeFacility/index.js, lambda/writePark/index.js, lambda/writePass/index.js
BRS-642
https://bcparksdigital.atlassian.net/browse/BRS-642
This is fixes an issue (1. in the comments), with facility edits on non-sysadmins.  Additionally, unified logger interface defaults to error, and minimizes output on the `npm run test` run, as well as our prod logging facility.  Can be changed at runtime with env var in the lambda(s).
=> BRS-642: Updates for facility/role handling as well as unified logger.

migrations/20220630151019-addFacilityIsUpdating.js
BRS-690
https://bcparksdigital.atlassian.net/browse/BRS-690
This ticket adds a facility lock attribute `isUpdating` to existing facilities. Changes that leverage this attribute, i.e. in the `writeFacility` lambda, will come in the future with the upcoming changes to the reservations objects.
=> BRS-690: Migration - add facility lock attribute to facilities

lambda/dynamoUtil.js
NOBUG
The `runQuery` and `runScan` functions in `dynamoUtil.js` only run until the DynamoDB Query/Scan limit of 1MB is reached. 
This change leverages `LastEvaluatedKey` to loop through queries/scans until finished if they go over the 1MB limit.
Calling `runQuery` or `runScan` with the `paginated= true` argument will only return the first page of data up to the 1MB limit. 
The functionalites of `runQuery` and `runScan` remain unchanged for existing functions.
=> NOBUG - dynamoUtil runQuery/runScan improvements

lambda/exportPass/index.js
This fixes an error in variable initialization.
=> NOBUG: Fix error in variable.

migrations/20220705194715-passCreationDate.js
BRS-690
https://bcparksdigital.atlassian.net/browse/BRS-690
When this migration originally hit prod, the query to collect the passes for updating was limited by the 1MB DynamoDB Query limit. This change ensures that if this migration is run multiple times, passes that have already been updated are ignored. Due to the size of this migration, a progress readout was also added to the console.
This new migration relies on the updates to `runQuery` in #133.
The old migration will have to be removed from the migrations table in AWS DEV/TEST/PROD envs so it can be rerun.
=> BRS-690-3: Improvements to passCreationDate migration

__tests__/global/setup.js, __tests__/writePass.test.js, lambda/deletePass/index.js, lambda/dynamoUtil.js, lambda/readReservation/index.js, lambda/writeFacility/index.js, lambda/writePass/index.js, migrations/20220706230456-reservationField.js, serverless.yml, terraform/src/db.tf, terraform/src/main.tf, terraform/src/reservations.tf, terraform/src/warmUp.tf, yarn.lock
BRS-673, BRS-675, BRS-719
https://bcparksdigital.atlassian.net/browse/BRS-673
https://bcparksdigital.atlassian.net/browse/BRS-675
https://bcparksdigital.atlassian.net/browse/BRS-719
Reservations are no longer stored in facility objects. We now use a separate reservations object model to store information related to available passes, capacities, and capacity modifiers.
This ticket must be merged with the following PRs:
https://github.com/bcgov/parks-reso-admin/pull/115
https://github.com/bcgov/parks-reso-public/pull/164
=> BRS-673: Reservation object revision.

terraform/src/roles.tf
BRS-673
https://bcparksdigital.atlassian.net/browse/BRS-673
FIX: adding ConditionCheckItem to writeRole.
=> BRS-673: adding ConditionCheckItem to writeRole

terraform/src/roles.tf
BRS-735
https://bcparksdigital.atlassian.net/browse/BRS-735
Fixing error when reducing capacity.
=> BRS-735: Fixing error when reducing capacity

terraform/src/roles.tf
BRS-734
https://bcparksdigital.atlassian.net/browse/BRS-734
Fixing missing perm in deletePass.
=> BRS-734: fixing missing perm in deletePass

lambda/exportPass/index.js
BRS-673
https://bcparksdigital.atlassian.net/browse/BRS-673
This fixes an issue with export csv.
=> BRS-673: Export to CSV - Missing data

lambda/writeFacility/index.js
BRS-673
https://bcparksdigital.atlassian.net/browse/BRS-673
Fixing overbooked calculations.
=> BRS-673: Fixing overbooked calculations

migrations/20220706230456-reservationField.js
BRS-741
https://bcparksdigital.atlassian.net/browse/BRS-741
Fixing sk issue on res obj.
=> BRS-741: Fixing sk issue on res obj

lambda/writeFacility/index.js
BRS-749
https://bcparksdigital.atlassian.net/browse/BRS-749
The variable `passDiff` was being used to stored two different 'concepts' depending on certain conditions. In one case, `passDiff === 'change in capacity'` and in another, `passDiff === 'change in availability'`. This is causing errors in our availability calculations if there is ever a remainder of availability (ie a bulk booking pass moving to the overbooked state). 
`passDiff` has been differentiated and the code restructured to use the correct 'concepts'.
=> BRS-749: fixing calcs for bulk overbooked states

lambda/writeFacility/index.js
BRS-746
https://bcparksdigital.atlassian.net/browse/BRS-746
=> BRS-746: reinstating overbooked passes if capacity increased

lambda/writeFacility/index.js
BRS-761
https://bcparksdigital.atlassian.net/browse/BRS-761
If a new booking time is introduced, comparing the old and new capacities/availabilities etc will break since no old values exist. This change ensures we aren't looking for non-existent values.
Additionally, If a booking time is closed, all passes currently booked under the now closed time will be moved to the overbooked state. Introducing the booking time again will reinstate these overbooked passes.
=> BRS-761 fixing error when adding new pass types

terraform/src/main.tf, terraform/src/modifiers.tf
BRS-736
https://bcparksdigital.atlassian.net/browse/BRS-736
Adding writeModifier to apigateway.
=> BRS-736: adding writeModifier to apigateway

lambda/writePass/index.js
BRS-776
https://bcparksdigital.atlassian.net/browse/BRS-776
Temp proposed fix to duplicate email issues
=> BRS-776 - proposed fix to prevent duplicate emails

postman/BCParks Day Use Pass API.postman_collection.json, postman/Day Use Pass - DEV.postman_environment.json, postman/Day Use Pass - LOCAL.postman_environment.json, postman/Day Use Pass - TEST.postman_environment.json
Adding postman library and respective environments. PROD env not included for now. This library is meant to be a jumping off point, future edits can ensure that the library doubles as our API documentation since Postman is good with formatting this stuff. 
It would be nice if the library is updated in tandem with any future endpoints that are created, so that peer reviewers and QA don't have to setup the endpoints themselves.
=> NOBUG - Adding Postman Library for API changes

lambda/writeModifier/index.js
BRS-736
https://bcparksdigital.atlassian.net/browse/BRS-736
This fixes a bug in the error handler.
=> BRS-736: Fix bug in obj variable scope.

lambda/readReservation/index.js
BRS-744
https://bcparksdigital.atlassian.net/browse/BRS-744
Adding ability to get list of future res objs. This is so we can get a modifiers list.
=> BRS-744: Adding ability to get list of future res objs

lambda/reservationObjUtils.js, lambda/writeModifier/index.js
=> NOBUG: Fix short date handling.

lambda/reservationObjUtils.js
NOBUG
Fixing issues with process res objs.
=> NOBUG: Fixing issues with process res objs

lambda/reservationObjUtils.js
NOBUG
Fixing issue where no timeslot exists on resObj.
=> NOBUG: Fixing issue where no timeslot exists on resObj

lambda/reservationObjUtils.js
NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-123
Fixing issue while removing timeslot.
=> NOBUG: Fixing issue while removing timeslot.

lambda/writeModifier/index.js
NOBUG
Prevent modifiers from accepting anything but shortDate, otherwise new resobj is made with invalid sk.
=> NOBUG - modifiers enforce shortDate

__tests__/writePass.test.js, lambda/writeFacility/index.js, lambda/writePass/index.js, migrations/20220818192715-facilityWeekendsOnlyUpdate.js
BRS-768
https://bcparksdigital.atlassian.net/browse/BRS-768
This change encompasses the BE portion of enabling users to change the days of the week on which a facility is bookable, as well as adding specific holiday dates that can override days that do not require a pass and enforce bookings. There is a minor front end portion that goes along with this change (https://github.com/bcgov/parks-reso-admin/pull/123) such that editing facilities with `admin` does not cause errors. 
The FE portion of this change will be handled in an upcoming ticket.
=> BRS-768 pt 1: BE changes to allow for weekend bookings

lambda/writePass/index.js
BRS-812
https://bcparksdigital.atlassian.net/browse/BRS-812
API fix for BRS-812
=> BRS-812 weekday localization in API

tools/extract-reserved-and-expired-people-counts.js
BRS-592 
https://bcparksdigital.atlassian.net/browse/BRS-592 
This adds a simple script to post-process a dump from the database.  This will not affect prod api at all.
=> BRS-592: Adding simple script to dump reports after a DB dump.

lambda/deletePass/index.js, lambda/dynamoUtil.js, lambda/writePass/index.js
BRS-796
https://bcparksdigital.atlassian.net/browse/BRS-796
This creates a new audit object for new passes moving forward.  Even though there are old passes in the system and DUP is closed for the season, the logic accounts for any passes that might be cancelled/requested to be such prior to this model change.
1. A change defined by `system` is when a new pass is created, `checkActivation` or `checkExpiry` jobs run and end up changing the pass status.
2. A change defined by `public` is when a user cancels their pass.
3. A changed defined by `admin` is when an administrator cancels the pass.
`dateUpdated` is always touched on every edit.
Example audit entries:
```
[
{
"M": {
"passStatus": {
"S": "active"
},
"by": {
"S": "system"
},
"dateUpdated": {
"S": "2022-10-12T21:24:10.917Z"
}
}
},
{ …
```
=> BRS-796: Add Audit values to passes in DUP

lambda/dynamoUtil.js, lambda/exportAllPass/GET/index.js, lambda/exportAllPass/functions.js, lambda/exportAllPass/invokable/index.js, serverless.yml, terraform/src/exportAll.tf, yarn.lock
BRS-592
https://bcparksdigital.atlassian.net/browse/BRS-592
Api work to export invokable pass data.
=> BRS-592: Api work to export invokable pass data.

lambda/metric/index.js
BRS-815
https://bcparksdigital.atlassian.net/browse/BRS-815
This improves the metric API endpoint call (Commit on behalf of @wilwong89 )
NB: Cookies to @wilwong89
=> BRS-815: Improve metrics endoint API call.

terraform/src/roles.tf
Co-authored-by: Wilson Wong <wilwong89@users.noreply.github.com>
BRS-815
https://bcparksdigital.atlassian.net/browse/BRS-815
This allows metrics lambda to hit the indexes it needs.
=> BRS-815: Terraform config update for metric call.

lambda/writePass/index.js
BRS-917
https://bcparksdigital.atlassian.net/browse/BRS-917
Weekdays use index instead of name.
=> BRS-917: weekdays use index instead of name

package.json, yarn.lock
This upgrades a few packages that have potentially breaking changes.
=> NOBUG: Package and security updates.

terraform/src/warmUp.tf
BRS-959
https://bcparksdigital.atlassian.net/browse/BRS-959
Adjusting cron for winter time operation..
=> BRS-959: adjusting warmup cron for PST

lambda/permissionUtil.js, package.json, tools/keycloakUserMigration.js, yarn.lock
BRS-861
https://bcparksdigital.atlassian.net/browse/BRS-861
This moves our OIDC from KC Silver => KC Gold.  Must be done in conjunction with
=> BRS-861: Investigate & migrate  to keycloak gold

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
BRS-961
https://bcparksdigital.atlassian.net/browse/BRS-961
Changing artifact directory to be just short hash.
=> BRS-961: Changing artifact directory to be just short hash

__tests__/writeFacility.test.js, __tests__/writePark.test.js, __tests__/writePass.test.js, lambda/captchaUtil.js, lambda/deletePass/index.js, lambda/readPass/index.js, package.json, yarn.lock
NOBUG
This bumps jsonwebtoken to v9 and uses specified signature algo in order to address a security vulnerability.
=> NOBUG: Bumps jsonwebtoken to v9 and uses specified signature algo.

lambda/passUtils.js
BRS-1002
https://bcparksdigital.atlassian.net/browse/BRS-1002
Update env var checking.
=> BRS-1002: Update env var checking.

__tests__/writePass.test.js, lambda/writePass/index.js, serverless.yml, terraform/src/main.tf, terraform/src/pass.tf
BRS-999
https://bcparksdigital.atlassian.net/browse/BRS-999
This adds a `checkedIn` `true/false` field on each pass to support the admin UI functions.  Payload to the back-end is an `HTTP PUT` with query string parameter `checkedIn=true` or `checkedIn=false` and body `{ pk: pk, sk: sk }` where pk = the pass PK and sk = the pass SK in question.
=> BRS-999: API Changes to allow checkedIn property in DB.

terraform/src/pass.tf
This is updates the put pass statement ID.
=> NOBUG: Update put pass statement id

terraform/src/main.tf, terraform/src/pass.tf
NOBUG: Remove legacy integration.
=> Remove legacy integration.

terraform/src/main.tf, terraform/src/pass.tf
Reverts bcgov/parks-reso-api#213
=> Revert "Remove legacy integration."

terraform/src/pass.tf
This creates a new statment_id for the new put api permission.
=> NOBUG: Create new statement_id

__tests__/writePass.test.js, lambda/writePass/index.js
BRS-999
https://bcparksdigital.atlassian.net/browse/BRS-999
This adjusts what the pk requirement for passing into a check-in time will be.
=> BRS-999: Adjust pk requirement.

__tests__/writePass.test.js, lambda/dynamoUtil.js, lambda/writePass/index.js
BRS-1029
https://bcparksdigital.atlassian.net/browse/BRS-1029
Setting up our `writePass` lambda to allow testers to book passes under the same email address multiple times for the same facility/day combination (still disabled in PROD).
Particularly helpful when testing GCN features as there is only a limited number of allowed email addresses within our GCN test enviroment safelist.
=> BRS-1029 allow duplicate bookings when not in prod

lambda/writePark/index.js
NOBUG
Sending back unmarshalled obj after update park.
=> NOBUG: sending back unmarshalled obj after update park.

__tests__/writePass.test.js, lambda/writePass/index.js, terraform/src/pass.tf
BRS-1055
https://bcparksdigital.atlassian.net/browse/BRS-1055
This adds unit tests for passes in the back-end, updating debug output on writepass
=> BRS-1055: Adding unit tests for passes in the back-end, updating debug output on writepass.

.github/workflows/PR-Tests.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Updating PR-Tests workflow.
=> BRS-1051: updating PR-Tests workflow

.github/workflows/PR-Tests.yaml, .github/workflows/deploy-dev.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Streamlining deploy dev workflow.
=> BRS-1051: Streamlining deploy dev workflow

.github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Using cache for artifacts.
=> BRS-1051: Using cache for artifacts

.github/workflows/on-pr.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Updating job name.
=> BRS-1051: updating job name

lambda/sendReminder/index.js
BRS-1044
https://bcparksdigital.atlassian.net/browse/BRS-1044
Update send reminder qr code lookup.
=> BRS-1044: Update send reminder qr code lookup.

terraform/src/reminderJob.tf, terraform/src/surveyJob.tf, terraform/src/warmUp.tf
BRS-1069
https://bcparksdigital.atlassian.net/browse/BRS-1069
This updates the times the lambdas run stick to the local times as specified in the ticket.
=> BRS-1069: Updating times for cronjobs.

lambda/writePass/index.js
This fixes legacy pass writing logic for older front-ends.
=> NOBUG: Fix legacy pass writing logic for older front-ends.

__tests__/readPass.test.js, lambda/readPass/index.js
BRS-1095
https://bcparksdigital.atlassian.net/browse/BRS-1095
`isAdmin` => `isAuthenticated`
=> BRS-1095 fixing non-sysadmin auth

__tests__/writePass.test.js, lambda/readPass/index.js, lambda/websocket/index.js, lambda/writePass/index.js
BRS-1095
https://bcparksdigital.atlassian.net/browse/BRS-1095
This adds an additional check on authenticated users for filter park queries only if they have the park role.
=> BRS-1095: Fix for role filtering on park.

terraform/src/roles.tf
BRS-1020
https://bcparksdigital.atlassian.net/browse/BRS-1020
Extraneous `,`
=> BRS-1020 tf roles typo

lambda/sqsProcessor/index.js
BRS-1056
https://bcparksdigital.atlassian.net/browse/BRS-1056
This changes the output that the logger does upon sending data to GCN.
=> BRS-1056: Adjust logger output.

lambda/sqsProcessor/index.js, lambda/sqsUtils.js, terraform/src/pass.tf
BRS-1056
https://bcparksdigital.atlassian.net/browse/BRS-1056
This reduces the amount of logging in sqsProcessor.
=> BRS-1056: Reduce logging levels.

terraform/src/cloudwatchAlarms.tf, terraform/src/db.tf, terraform/src/sqs.tf
NOBUG
Adding `${env_identifier}` to sqs functions.
=> NOBUG: adding unique ids to sqs fn names

yarn.lock
This updates the package lock dependency file.
=> NOBUG: Package updates to lock file.

lambda/writePass/index.js
BRS-1099
https://bcparksdigital.atlassian.net/browse/BRS-1099
Change PM slot opening hour from 12pm -> 1pm. This change is paired with a change in the frontend as part of BRS-1099.
=> BRS-1099: Change PM slot opening hour from 12pm -> 1pm

serverless.yml
BRS-1139
This fixes path packaging with serverless.
=> BRS-1139: Fixing packaging paths in build.

serverless.yml
BRS-1139
This removes node_modules from includes.
=> BRS:1139: Fixing includes for packages.

serverless.yml
Reverts bcgov/parks-reso-api#264
=> Revert "BRS:1139: Fixing includes for packages."

.github/workflows/deploy-dev.yaml
BRS-1139
Update workflow for file limits.
=> BRS-1139: Update workflow.

yarn.lock
BRS-1139
This updates the axios package.
=> BRS-1139: Updated axios package.

lambda/readReservation/index.js
BRS-1168
https://bcparksdigital.atlassian.net/browse/BRS-11688
Modifier service was only returning the first modifier in the list.
=> BRS-1168 modifier list should show all future modifiers

CODEOFCONDUCT.md, README.md
BRS-1204
https://bcparksdigital.atlassian.net/browse/BRS-123
This is a description.
=> BRS-1204: Updated README.md and COC

README.md
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Documentation.
=> BRS-1152: Documentation.

lambda/writePass/index.js
NOBUG
Adding registration number to writePass logs for ease of identification.
=> NOBUG: adding registration number to writePass logs

lambda/writePass/index.js
This adds a bit more verbosity to the log file.
=> NOBUG: Update logger with more information.

lambda/writePass/index.js
Update the logger with stringify object.
=> NOBUG: Update logger

__tests__/captchaHandler.test.js, __tests__/writePass.test.js, lambda/captcha/handler.js, lambda/captchaUtil.js, lambda/passUtils.js, lambda/writePass/index.js
BRS-1251
https://bcparksdigital.atlassian.net/browse/BRS-1251
Preventing replay attack on write pass.
This code requires https://github.com/bcgov/parks-reso-public/pull/250
=> BRS-1251: Preventing replay attack on write pass

lambda/writePass/index.js
=> NOBUG logic update

lambda/writePass/index.js
=> NOBUG logic improvements 2

__tests__/captchaHandler.test.js, __tests__/writePass.test.js, lambda/captcha/handler.js, lambda/captchaUtil.js, lambda/passUtils.js, lambda/writePass/index.js
This updates the negotiated logic.
=> NOBUG: Updating logic c/o @cameronpettit

terraform/src/captcha.tf
=> NOBUG: Update logger.

lambda/captchaUtil.js
=> NOBUG: Adding more logging.

terraform/src/captcha.tf, terraform/src/pass.tf, terraform/src/reservations.tf
=> NOBUG: Updating env vars/logging.

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-pr.yaml
=> NOBUG: Updating workflows

docs/DUP_DataModel.json
PDR-288
https://github.com/bcgov/parks-reso-api/issues/288
Adding NoSQL workbench documentation for data model.
=> PDR-288 creating noSQL workbench data model

__tests__/writePark.test.js, __tests__/writePass.test.js, lambda/responseUtil.js, terraform/src/export.tf, terraform/src/exportAll.tf, terraform/src/facility.tf, terraform/src/main.tf, terraform/src/metric.tf, terraform/src/metrics.tf, terraform/src/modifiers.tf, terraform/src/modules/cors-enabled-api-resource/variables.tf, terraform/src/pass.tf, terraform/src/reservations.tf, terraform/src/settings.tf
This adds version header information to header requests.
=> NOBUG: Add version header capability

__tests__/updateParkNames.test.js, lambda/dataRegisterUtils.js, lambda/updateParkName/index.js, serverless.yml, terraform/src/params.tf, terraform/src/updateParkNames.tf
Features https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=35021949
=> PDR-288 Linking DUP to DR and pull data on nightly cron

terraform/src/updateParkName.tf
`updateParkNames` should be `updateParkName`
=> PDR-23 mislabelled tf function

terraform/src/variables.tf
Update the parameter in the parameter store.
=> 122: Update parameter.

terraform/src/reminderJob.tf, terraform/src/surveyJob.tf, terraform/src/warmUp.tf
BRS-314
[https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42235243](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42235243)
Updated cron jobs to trigger at appropriate times for winter
=> BRS-314: Updated cron jobs to trigger at appropriate times for winter

serverless.yml
Fixes build issues in serverless.com configuration.
=> NOBUG: Fix serverless.com build issue.

lambda/sendReminder/index.js, lambda/smsUtil.js, terraform/src/params.tf, terraform/src/reminderJob.tf
BRS-278
[BRS-278](https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=42222375)
- Added functionality to send SMS notifications to users through gcNotify
- Included SMS feature in the email notification sequence 
- Updated terraform file to look for new env-var in parameter store
=> Send SMS with reminder email to passes which have phone numbers

lambda/smsUtil.js
BRS-278
[BRS-278](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42222375)
Fixing typo in object sent to GCNotify. Misspelled name did not match the template causing SMS to not send.
=> BRS-278: Fix Bug for SMS

lambda/smsUtil.js
BRS-278
[BRS-278](
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42222375)
Changed pass type value to lower case before being sent in sms.
=> BRS-278: Fix - Change Format of AM/PM/DAYUSE

lambda/smsUtil.js
BRS-299
[BRS-299](https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=46681304)
Adjusted wording sent to gcNotify. 
Adjusted formatting sent to gcNotify. 
Remove prefix to on phone number sent to gcNotify to allow for international numbers.
=> BRS-299: International Phone numbers + Update Template

lambda/readFaq/index.js, lambda/writeFaq/index.js, serverless.yml, terraform/src/faq.tf
BRS-337
[337](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47365823)
Add endpoint to API to handle the GET and PUT requests for FAQ pages
=> Add FAQ endpoint with GET and PUT

terraform/src/faq.tf
[BRS-337
](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47365823)
[BRS-337
](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47365823)
Updating TF file to allow API-Gateway to connect with Lambda
=> Changing TF file for FAQ endpoints

terraform/src/reminderJob.tf, terraform/src/surveyJob.tf, terraform/src/warmUp.tf
BRS-352
[BRS-352](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=55327884)
Changing the cron schedule for sending reminder notification, sending surveys, and daily warmup to align with daylight savings.
=> BRS-352: Adjusting schedule of crons for daylight savings

lambda/writePass/index.js
[BRS-368](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=60245050)
[BRS-368](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=60245050)
Parameter being passed to GCN was nested within passObject. Changed the way it is being accessed
parkData was a not defined, changed the orc to grabbed from passObject
=> FIX: Update to email parameter being passed to GCN

lambda/writePass/index.js
[BRS-368](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=60245050)
[BRS-368](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=60245050)
Updated email parameter being passed to GCNotify to correctly use the users email.
=> BRS-368:Fix email for GCNotify

lambda/dynamoUtil.js
Creating variable for DB endpoint override.
=> NOBUG: creating variable for DB endpoint override.

lambda/dynamoUtil.js
Relates to [#359
](https://github.com/bcgov/parks-reso-public/issues/359)
Changes the PM opening hour to 1300 (1pm)
=> PDR-359 update PM opening hour to 1pm

terraform/src/pass.tf
=> DUP-336: Adding env var for CF_SECRET_KEY in TF

lambda/writePass/index.js
Put the timer into a variable.
=> ENV Var hold pass timer for back-end.

lambda/dynamoUtil.js, lambda/purgeExpired/index.js, terraform/src/expirySQS.tf, terraform/src/pass.tf
Adds the sqs queue for purging expired JWT's
=> 336: Adding sqs queue for purging expired JWT's

__tests__/writePass.test.js, lambda/writePass/index.js
`writePass` lambda throws error now when pass is unavailable to be held.
=> PDR-355 improving response when pass fails to hold

lambda/deletePass/index.js
=> NOBUG: Update index.js

samNode/template.yaml
No Ticket:  - Changing bucket name so Sam can build for initial deploy
=> BRS-336: Template fix

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, samNode/layers/passLayer/passLayer.js, samNode/template.yaml
Ticket: [336](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47054955)
Notes: Adding sqs info to workflow as discovered from QA.
=> BRS;336 Sendbacks from QA

samNode/handlers/readFacility/index.js
Ticket: [BRS-424](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70969356)
* Added time to response in get request on facilities
* Used to determine actual time when comparing against booking window on public
=> BRS-424: Passes are bookable prior to 7am

.github/workflows/analysis.yaml, samNode/layers/baseLayer/baseLayer.js, samNode/template.yaml
Ticket: [BRS-421](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=86244105&issue=bcgov%7Cparks-reso-api%7C421)
Notes: Doing the opposite of what was done in the past. Some of the crons had not been set up in SAM yet so that has been added. Changed the PM expiry times to match what was required for last year at this time.
=> BRS-421: Changes for end of daylight savings

samNode/template.yaml
Ticket: [421](https://github.com/orgs/bcgov/projects/49/views/1?filterQuery=-no%3Astatus+sprint%3A%40current+-status%3A%22SME+Reviewed%22%2CIcebox%2CTBC++421&pane=issue&itemId=86244105&issue=bcgov%7Cparks-reso-api%7C421)
Notes: Check activation function was not working. Added missing layer to SAM template.
=> BRS-421: Change to pacific standard time

.github/workflows/analysis.yaml, samNode/template.yaml
Notes: 
* Added public frontend var to writepass lambda to be used in cancelation link
* Removed trivvy from on PR
=> NOTICKET: Bugfix for cancelation links

samNode/template.yaml
Notes:
* Used all caps REF in last PR. Fixed that Caps Lock typo.
=> NOBUG - Fix typo 

migrations/archiveMigration.js
Ticket: [384](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57003519&issue=bcgov%7Cparks-reso-admin%7C384)
Notes: 
Migration to archive passes from 2021-2022
Pending approval of this next step will be to create a lambda to automatically run at desired time each year (Time to be determined) incrementing the year to archive all old passes.
=> BRS:384 - Archive Old Passes

samNode/template.yaml
No ticket: Increasing timeout for sendReminder to manage timeout on busy weekends
=> NOTICKET-Increase Timeout

samNode/handlers/archivePasses/index.js
Ticket: [384](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57003519&issue=bcgov%7Cparks-reso-admin%7C384)
Notes: Testing failed while running against a very small set passes to be archived. Initial logic didn't take into account minimal passes not requiring a last key scanned. Updated to do while so even with 1 pass it will archive the pass.
=> BRS:384 - Archive fix

samNode/layers/metricsLayer/metricsLayer.js
BRS-312
[#312](https://github.com/bcgov/parks-reso-admin/issues/312)
- Check `passesRequired` and set the `baseCapacity` and `availablePasses` earlier in the `createMetric` function. Will properly apply any changes to capacity and available passes when the cron runs.
=> BRS-312-1: Fix Site Metrics Results when Facilities were Noted as "Pass Not Required"

samNode/template.yaml
Ticket: [504](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=104931620&issue=bcgov%7Cparks-reso-public%7C504)
Notes: Correcting the Cron schedule I did wrong last time; as discovered in QA.
=> BRS-504:Daylight Fix

samNode/handlers/writeModifier/index.js
- Fixed formatting issues in `handler` function, including spacing and error message structure.
- Added detailed JSDoc comments for the `updateModifier` function to describe its purpose, parameters, and return value.
- Implemented `updateModifier` function to update capacity modifiers for reservation objects:
- Ensures the facility and booking times are valid.
- Validates that new total capacities are not negative before applying modifiers.
- Processes reservation objects with updated modifiers.
- Improved logging for debugging, including detailed capacity calculations.
**NB**: There will be a separate PR for updating the UI toast message in the admin repository.
=> 403: Improve error handling and add updateModifier function

samNode/layers/baseLayer/baseLayer.js
Ticket: [405](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=107867296&issue=bcgov%7Cparks-reso-admin%7C405)
Notes: Similar to previous [Commit](https://github.com/bcgov/parks-reso-api/commit/37a40aec173c97b8a5205408861336d1370e9120).
=> BRS-405: Change AM pass expiry time

samNode/layers/baseLayer/baseLayer.js
Ticket: [407](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=108652558&issue=bcgov%7Cparks-reso-admin%7C407)
Notes: Bug resulted from only adjusting PM opening time in ticket [405](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=107867296&issue=bcgov%7Cparks-reso-admin%7C405)
=> BRS-407: Change AM Expiry Time
